### ISSUE TITLE
Right-main-simulation-file.R: error message related cost file

### ISSUE THREAD

**Issue by Labeit** [spgarbet/right#1]
If I run the right-main-simulation-file.R
some warnings (but not critical)
then error message:
> source("./costs.R") > x <- costs(env, inputs)
> x <- costs(env, inputs)
> Error in discounted_cost(arrivals$start_time, end_time, 365): 
 object 'end_time' not found 
 Called from: discounted_cost(arrivals$start_time, end_time, 365)
 
[Error  message_rightsim_15012020_AL.pdf](https://github.com/spgarbet/right/files/4065889/Error.message_rightsim_15012020_AL.pdf)

**Comment by spgarbet** [comment]
I don't know what changed, but something in upgrading packages broke a lot.

**Comment by Labeit** [comment]
Dear Shawn,

thanks for the info.
What is best for me to do do know?

1. To wait until you have fixed the problem with dplyr.
2. To use an older version of the library dplyr if possible?

Thanks in advance again,
Alexander

**Comment by spgarbet** [comment]
See if this works for you.
